# Generated by Django 4.2.8 on 2024-02-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('state', models.CharField(choices=[('Jaipur', 'Jaipur'), ('Kota', 'Kota'), ('Jodhpur', 'Jodhpur'), ('Nagaur', 'Nagaur')], max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
